### ISSUE TITLE
Training Code Execution Problem

### ISSUE THREAD

**Issue by MahbubSohel** [raaj043/Age-Estimation--DEX-in-Pytorch#4]
Hi @raaj043 ,
I didn't found a file named 'IMDB_Wiki_Adience_Train_Undersample_Dist.csv' in your repository that is needed to execute the training code. Can you please provide me the above-mentioned file. I already read your comments on issue#3 but still confused about that. I will be very grateful to you if you provide me the file or details about how you made this file. Thank you very much.
  
![Screenshot from 2020-04-30 17-23-50](https://user-images.githubusercontent.com/50574470/80688832-62fcfb80-8b07-11ea-8421-0301538e61a1.png)

**Comment by basavaraj-hampiholi** [comment]
Hello,
I have used Adience dataset to include more images. You can use just IMDB-WIKI dataset. I think thats more than enough. All the precessing files are in source_code preprocessing folder.

Here is the undersampled csv file. 
https://github.com/raaj043/Age-Estimation--DEX-in-Pytorch/blob/master/IMDB_WIKI/file_paths/imdb_wiki_adience_dataset_undersample.csv

Source code for undersampling csv file is here. 
https://github.com/raaj043/Age-Estimation--DEX-in-Pytorch/blob/master/SourceCode_Preprocessing/undersampling.py

Please let me know the if you need any more help!

**Comment by MahbubSohel** [comment]
> Hello,
> I have used Adience dataset to include more images. You can use just IMDB-WIKI dataset. I think thats more than enough. All the precessing files are in source_code preprocessing folder.
> 
> Here is the undersampled csv file.
> https://github.com/raaj043/Age-Estimation--DEX-in-Pytorch/blob/master/IMDB_WIKI/file_paths/imdb_wiki_adience_dataset_undersample.csv
> 
> Source code for undersampling csv file is here.
> https://github.com/raaj043/Age-Estimation--DEX-in-Pytorch/blob/master/SourceCode_Preprocessing/undersampling.py
> 
> Please let me know the if you need any more help!

Hello raaj043,
Thanks for your prompt reply. I just used IMDB-WIKI dataset as you suggested. I will ask for your attention if I need further assistance.

**Comment by MahbubSohel** [comment]
Hi @raaj043,
Hope you are doing fine. I also add Adience images with IMDB-WIKI images for training. But I don't understand how you annotated exact age from the age range. As we know adience image dataset contains only age range.
